import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/providers/ThemProvider";
import { TooltipProvider } from "@/providers/TooltipProvider";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "@/providers/UserProvider";
import { userService } from "@/services/user.service";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // get sesion and  sent to provider
  const sessionResponse = await userService.getSession();
  const user = sessionResponse.data?.user || null;


  return (
    <html lang="en" suppressHydrationWarning  >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UserProvider initialUser={user} >
            {/* here wil be all Providers */}


            <TooltipProvider>

              {children}

              <Toaster richColors />

            </TooltipProvider>

          </UserProvider>

        </ThemeProvider>


      </body>
    </html>
  );
}
